### ISSUE TITLE
Unknown function "cl-cddr"

### ISSUE THREAD

**Issue by grimnebulin** [AdamNiederer/elquery#2]
The function `elquery--parse-libxml-tree` calls a function `cl-cddr` that doesn't exist.

**Comment by zonuexe** [comment]
This problem seems to committed in  https://github.com/AdamNiederer/elquery/commit/ef9a8c82fce614297e267961fbdd90aceba606a7 .

`cddr` does not have `cl-` prefix because [`cddr` is defined in `subr.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/subr.el#L386-L389).

**Comment by AdamNiederer** [comment]
Ooh, thanks for catching that. Fixed in 084301b1.

I should probably get a test suite going.
