### ISSUE TITLE
Add elquery into MELPA?

### ISSUE THREAD

**Issue by stardiviner** [AdamNiederer/elquery#4]
I found currently MELPA does not have any packages read and manipulate HTML data right now. So I searched GitHub. found this elquery. I hope this can be available in MELPA. WDYT?

**Comment by AdamNiederer** [comment]
It is! https://melpa.org/#/elquery

**Comment by stardiviner** [comment]
Sorry for this.

**Comment by AdamNiederer** [comment]
No problem!
