### ISSUE TITLE
elquery uses `insert-string`, which isn't defined in core emacs 26.1, or any dependency of the melpa package

### ISSUE THREAD

**Issue by slippycheeze** [AdamNiederer/elquery#7]
elquery uses `insert-string`, which isn't defined in core emacs 26.1, or any dependency of the melpa package.

This is used exclusively in the `elquery-read-string` function, and would be just as well served by using either of `(insert string)` -- if it isn't already a string, pretty sure it won't parse with libxml anyway. :)

**Comment by AdamNiederer** [comment]
Thanks for the heads up. Fixed in eac429d.
